backend/config/routes.rb
Rails.application.routes.draw do
  resources :job_tags

  resources :tags

  resources :jobs

  resources :companies

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

backend/app/models/job.rb
class Job < ActiveRecord::Base
belongs_to :company
has_many :job_tags
has_many :tags, through: :job_tags

  def tag_list
    self.tags.map { |t| t.name }.join(", ")
  end

end

backend/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :set_companies_for_template, only: [:new, :edit]

  before_filter :authorize, :except => ['index', 'show']

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.where("jobs.end >= ? OR jobs.end IS NULL", Date.today).includes(:tags)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    params.permit(:tag_list)
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save

        tag_names = params[:job][:tag_list].split(/,\s+/)
        tag_names.each { |name|
          tag = Tag.find_or_create_by(name: name.strip)

          puts 'TAGIN TIEDOT'
          puts @job.id
          puts tag.id

          JobTag.find_or_create_by(:job_id => @job.id, :tag_id => tag.id)

        }

        #JobMailer.job_mail(@job).deliver_now
        #send_job_to_irc(@job)

        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def send_job_to_irc(job)
    require "net/http"
    require "uri"

    uri = URI.parse("http://bot.synyker.eu/job")
    Net::HTTP.post_form(uri, {"title" => @job.title, "company" => @job.company.name, "id" => @job.id })

  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    params.permit(:tag_list)

    respond_to do |format|
      if @job.update(job_params)

        tag_names = params[:job][:tag_list].split(/,\s+/)
        tag_names.each { |name|
          tag = Tag.find_or_create_by(name: name.strip)
          JobTag.find_or_create_by(:job_id => @job.id, :tag_id => tag.id)
        }

        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    def set_companies_for_template
      @companies = Company.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :company_id, :description, :begin, :end)
    end
end

backend/app/helpers/jobs_helper.rb
module JobsHelper
end

backend/app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.select :company_id, options_from_collection_for_select(@companies, :id, :name, :selected => f.object.company_id) %>
  </div>

  <div class="field">
    <p>Käytä <a target="_blank" href="https://word2cleanhtml.com/">https://word2cleanhtml.com/</a> descriptionin mailista html muuntamiseen.</p>
    <%= f.label :description %><br>
    <%= f.text_area :description, :cols => "100", :rows => "18" %>
  </div>
  <div class="field">
    <%= f.label :begin %><br>
    <%= f.date_select :begin %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.date_select :end, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

backend/app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Company</th>
      <th>Description</th>
      <th>Begin</th>
      <th>End</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.company_id %></td>
        <td><%= job.begin %></td>
        <td><%= job.end %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

backend/app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

backend/app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Company:</strong>
  <%= @job.company_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Begin:</strong>
  <%= @job.begin %>
</p>

<p>
  <strong>End:</strong>
  <%= @job.end %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>