backend/config/routes.rb
Rails.application.routes.draw do
  resources :job_tags

  resources :tags

  resources :jobs

  resources :companies

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

backend/app/models/job_tag.rb
class JobTag < ActiveRecord::Base
  belongs_to :job
  belongs_to :tag
end

backend/app/controllers/job_tags_controller.rb
class JobTagsController < ApplicationController
  before_action :set_job_tag, only: [:show, :edit, :update, :destroy]

  before_filter :authorize, :except => ['index', 'show']

  # GET /job_tags
  # GET /job_tags.json
  def index
    @job_tags = JobTag.all
  end

  # GET /job_tags/1
  # GET /job_tags/1.json
  def show
  end

  # GET /job_tags/new
  def new
    @job_tag = JobTag.new
  end

  # GET /job_tags/1/edit
  def edit
  end

  # POST /job_tags
  # POST /job_tags.json
  def create
    @job_tag = JobTag.new(job_tag_params)

    respond_to do |format|
      if @job_tag.save
        format.html { redirect_to @job_tag, notice: 'Job tag was successfully created.' }
        format.json { render :show, status: :created, location: @job_tag }
      else
        format.html { render :new }
        format.json { render json: @job_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_tags/1
  # PATCH/PUT /job_tags/1.json
  def update
    respond_to do |format|
      if @job_tag.update(job_tag_params)
        format.html { redirect_to @job_tag, notice: 'Job tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_tag }
      else
        format.html { render :edit }
        format.json { render json: @job_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_tags/1
  # DELETE /job_tags/1.json
  def destroy
    @job_tag.destroy
    respond_to do |format|
      format.html { redirect_to job_tags_url, notice: 'Job tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_tag
      @job_tag = JobTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_tag_params
      params.require(:job_tag).permit(:job_id, :tag_id)
    end
end

backend/app/helpers/job_tags_helper.rb
module JobTagsHelper
end

backend/app/views/job_tags/_form.html.erb
<%= form_for(@job_tag) do |f| %>
  <% if @job_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_tag.errors.count, "error") %> prohibited this job_tag from being saved:</h2>

      <ul>
      <% @job_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job_id %><br>
    <%= f.number_field :job_id %>
  </div>
  <div class="field">
    <%= f.label :tag_id %><br>
    <%= f.number_field :tag_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/app/views/job_tags/edit.html.erb
<h1>Editing Job Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_tag %> |
<%= link_to 'Back', job_tags_path %>

backend/app/views/job_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Job Tags</h1>

<table>
  <thead>
    <tr>
      <th>Job</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_tags.each do |job_tag| %>
      <tr>
        <td><%= job_tag.job_id %></td>
        <td><%= job_tag.tag_id %></td>
        <td><%= link_to 'Show', job_tag %></td>
        <td><%= link_to 'Edit', edit_job_tag_path(job_tag) %></td>
        <td><%= link_to 'Destroy', job_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job tag', new_job_tag_path %>

backend/app/views/job_tags/new.html.erb
<h1>New Job Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', job_tags_path %>

backend/app/views/job_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job:</strong>
  <%= @job_tag.job_id %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @job_tag.tag_id %>
</p>

<%= link_to 'Edit', edit_job_tag_path(@job_tag) %> |
<%= link_to 'Back', job_tags_path %>